# Generated by Django 5.1 on 2025-02-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_adminresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminresponse',
            name='close_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='adminresponse',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Awaiting Confirmation'), ('R', 'Resolved'), ('C', 'Closed')], default='P', max_length=1),
        ),
    ]
