# Generated by Django 5.1 on 2025-02-04 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_adminresponse_close_reason_adminresponse_is_closed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminresponse',
            name='close_reason',
        ),
        migrations.RemoveField(
            model_name='adminresponse',
            name='is_closed',
        ),
        migrations.AlterField(
            model_name='query',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('R', 'Resolved'), ('C', 'Closed')], default='P', max_length=1),
        ),
    ]
