# Generated by Django 5.1 on 2024-10-14 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='planned_expense',
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('food', 'Food'), ('travel', 'Travel'), ('entertainment', 'Entertainment'), ('electricity', 'Electricity'), ('medicine', 'Medicine'), ('groceries', 'Groceries'), ('bills', 'Bills'), ('loan', 'Loan'), ('insurance', 'Insurance'), ('transport', 'Transport'), ('subscriptions', 'Subscriptions'), ('clothing', 'Clothing'), ('household_supplies', 'Household Supplies'), ('dining_out', 'Dining Out'), ('gifts', 'Gifts'), ('miscellaneous', 'Miscellaneous'), ('charity', 'Charity'), ('education', 'Education'), ('dress', 'Dress'), ('gym', 'Gym'), ('custom', 'Add Any Other Expense')], max_length=100),
        ),
    ]
