# Generated by Django 5.1 on 2024-10-16 16:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('food', 'Food'), ('travel', 'Travel'), ('entertainment', 'Entertainment'), ('electricity', 'Electricity'), ('medicine', 'Medicine'), ('groceries', 'Groceries'), ('bills', 'Bills'), ('loan', 'Loan'), ('insurance', 'Insurance'), ('transport', 'Transport'), ('subscriptions', 'Subscriptions'), ('clothing', 'Clothing'), ('household_supplies', 'Household Supplies'), ('dining_out', 'Dining Out'), ('gifts', 'Gifts'), ('miscellaneous', 'Miscellaneous'), ('charity', 'Charity'), ('education', 'Education'), ('dress', 'Dress'), ('gym', 'Gym'), ('custom', 'Add Any Other Expense')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
